<?
//define('FULL_WIDTH', true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "Суперцена, распродажа");
$APPLICATION->SetPageProperty("description", "Суперцена, распродажа остатков");
$APPLICATION->SetTitle("Каталог");
?> <?$APPLICATION->IncludeComponent(
	"individ:catalog", 
	".default", 
	array(
		"SECTIONS_FILTER_NAME" => "",
		"AJAX_MODE" => "N",
		"SEF_MODE" => "Y",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "1",
		"USE_FILTER" => "Y",
		"USE_REVIEW" => "N",
		"USE_COMPARE" => "N",
		"SHOW_TOP_ELEMENTS" => "N",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "1",
		"PAGE_ELEMENT_COUNT" => "20",
		"LINE_ELEMENT_COUNT" => "1",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "ASC",
		"ELEMENT_SORT_FIELD2" => "sort",
		"ELEMENT_SORT_ORDER2" => "desc",
		"LIST_PROPERTY_CODE" => array(
			0 => "CML2_BASE_UNIT",
			1 => "CML2_SALE_UNIT",
			2 => "CML2_UNIT_QUANTITY",
			3 => "NODISCOUNT",
			4 => "NOT_SKID",
			5 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "UF_META_KEYWORDS",
		"LIST_META_DESCRIPTION" => "UF_META_DESCRIPTION",
		"LIST_BROWSER_TITLE" => "UF_META_TITLE",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "NODISCOUNT",
			1 => "NOT_SKID",
			2 => "",
		),
		"DETAIL_META_KEYWORDS" => "META_KEYWORDS",
		"DETAIL_META_DESCRIPTION" => "META_DESCRIPTION",
		"DETAIL_BROWSER_TITLE" => "META_TITLE",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "600",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "DISCOUNT",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"USE_PRODUCT_QUANTITY" => "Y",
		"LINK_IBLOCK_TYPE" => "catalog",
		"LINK_IBLOCK_ID" => "1",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "",
		"USE_ALSO_BUY" => "N",
		"USE_STORE" => "Y",
		"USE_ELEMENT_COUNTER" => "N",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "600",
		"PAGER_SHOW_ALL" => "N",
		"FILTER_NAME" => "arCatFILTER",
		"FILTER_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "CML2_BASE_UNIT",
			1 => "CML2_SALE_UNIT",
			2 => "CML2_UNIT_QUANTITY",
			3 => "",
		),
		"FILTER_PRICE_CODE" => array(
		),
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "N",
		"USE_MIN_AMOUNT" => "N",
		"STORE_PATH" => "/store/#store_id#",
		"MAIN_TITLE" => "Наличие на складах",
		"HIDE_NOT_AVAILABLE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"SEF_FOLDER" => "/catalog/",
		"COMPONENT_TEMPLATE" => ".default",
		"AJAX_OPTION_ADDITIONAL" => "undefined",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"discounts" => "discounts/",
			"novelty" => "novelty/",
			"novelty_section" => "novelty/#SECTION_CODE_PATH#/",
			"superprice" => "superprice/",
			"superprice_section" => "superprice/#SECTION_CODE_PATH#/",
			"superprice_element" => "superprice/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
			"residues" => "residues/",
			"residues_section" => "residues/#SECTION_CODE_PATH#/",
			"sale" => "sale/",
			"sale_section" => "sale/#SECTION_CODE_PATH#/",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		)
	),
	false
);?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>